version: "3.8"

#
# A simple compose file for running single zero and alpha
#
services:

  # Dgraph Zero controls the cluster
  zero:
    image: dgraph/dgraph:$DGRAPH_VERSION
    container_name: test_dgraph_zero
    volumes:
      - ~/test-dgraph-data:/dgraph
    ports:
      - 5080:5080
      - 6080:6080
    command: dgraph zero --my=zero:5080 --logtostderr -v=2 --telemetry sentry=false --trace "jaeger=http://jaeger:14268; ratio=1.0"
    restart: unless-stopped
  # Dgraph Alpha hosts the graph and indexes
  alpha:
    image: dgraph/dgraph:$DGRAPH_VERSION
    container_name: test_dgraph_alpha
    volumes:
      - ~/test-dgraph-data:/dgraph
    ports:
      - 8080:8080
      - 9080:9080
    command: >
      dgraph alpha --my=alpha:7080 --zero=zero:5080
        --security whitelist=0.0.0.0/0
        --logtostderr -v=2
        --telemetry sentry=false
        --trace "jaeger=http://jaeger:14268; ratio=1.0"
    restart: unless-stopped
  jaeger:
    image: jaegertracing/all-in-one:latest
    container_name: jaeger
    working_dir: /working/jaeger
    environment:
    - COLLECTOR_ZIPKIN_HTTP_PORT=9411
    - COLLECTOR_OTLP_ENABLED=true
    ports:
      - 6831:6831/udp
      - 6832:6832/udp
      - 5778:5778
      - 16686:16686
      - 4317:4317
      - 4318:4318
      - 14250:14250
      - 14268:14268
      - 14269:14269
      - 9411:9411
    command: --memory.max-traces=1000000
